### PR TITLE
Fix build priv dir

### LINKED ISSUE #1: priv dir not created in build dir
When using this package as a dependency in another project, the `priv` dir is not created.
This causes the symlink into the build directory to not be created by `mix`.
The solution is:

* Add a `.keep` file in the `priv` dir.
* Remove `priv` from `.gitignore` and instead explicitly ignore the generated bin file `priv/experhash`.

### PR DESCRIPTION
**Pull request by suranyami**
Fix #1:
* Changed `.gitignore` to only ignore `priv/experhash_port`, not whole directory.
* Added `priv/.keep` file to preserve directory in git history.
* Added explicit package definitions in `mix.exs`.
* Added ignore for `.DS_Store` to get rid of macOS kruft.
* Use `:code.priv_dir/1` to find `priv` directory in a portable way.
* Added image fixture used in tests.

### CODE REVIEW

**Comment by kemonomachi** [comment]
Nice! I'll take a look at this during the upcoming weekend

**Comment by suranyami** [comment]
Any progress on this?

Do you need a test repo that uses this to test that it works?

**Comment by kemonomachi** [comment]
Sorry for the late answer!

Don't really like keeping empty directories around, but if it works, I'll take it. Will test it out this Saturday. (Can fiddle with other solutions when I get some more time, better to get it working first)

Don't want any binary files in the repo, but the tests do need some kind of improvement. Will add a new issue for this instead.

No platform specific stuff in the .gitignore, please add it to your local git config instead.

:code.priv_dir/1 is brilliant, thank you!

**Comment by suranyami** [comment]
> No platform specific stuff in the .gitignore, please add it to your local git config instead.

I *do* have it in my local `~/.gitignore_global` but it still seems to want to add them.

I've removed it, and I'll check my git setup to see if I've messed something up.

**Comment by suranyami** [comment]
> Don't want any binary files in the repo, but the tests do need some kind of improvement.

Given that the function of the library is generating hashes and checking hamming distances of *binary files*, I'd argue that there should be binary fixtures in the tests. Admittedly, though, the one chosen is about 500kB, so there's a strong argument for something smaller.

I had toyed with the idea of making a http request to get the binary, and placing it in a directory that is in the `.gitignore` but that sounds brittle.

In the past, I've used robohash.org for this sort of thing, but they had a service outage not long ago which caused tests to break, so that's not such a good idea.

I think the best solution would be to have a small number of binary files that are not too big (10-20kB), visually unique and just leave it at that.

**Comment by kemonomachi** [comment]
I'm leaving the test image out for now, I've merged the rest.

>Given that the function of the library is generating hashes and checking hamming distances of binary files, I'd argue that there should be binary fixtures in the tests.

Yup, might just have to break the rule for this one. I vaguely remember planning on creating a set of small test images back when I first wrote this tool. Seems like a reasonable compromise. (Moving to a new apartment next month though, so it'll probably be a while before I get around to it.)

Anyway, thanks a bunch!

**Pull request closed without merging**
